import { NextRequest, NextResponse } from 'next/server';
import { auth } from '@/lib/auth';
import { supabaseAdmin } from '@/lib/supabase/server';

/**
 * GET /api/mock-test/credits
 * Returns the authenticated user's mock test credit balance.
 */
export async function GET(_req: NextRequest) {
  const session = await auth();
  if (!session?.user?.id) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const userId = session.user.id;

  // Total credits earned = sum of all paid purchases
  const { data: purchases, error: purchaseErr } = await supabaseAdmin
    .from('mock_test_purchases')
    .select('credits_granted')
    .eq('user_id', userId)
    .eq('status', 'paid');

  if (purchaseErr) {
    return NextResponse.json({ error: 'Failed to fetch credits' }, { status: 500 });
  }

  const totalEarned = (purchases ?? []).reduce(
    (sum: number, p: { credits_granted: number }) => sum + p.credits_granted,
    0
  );

  // Total used = number of sessions generated by this user
  const { count: totalUsed, error: sessErr } = await supabaseAdmin
    .from('mock_test_sessions')
    .select('id', { count: 'exact', head: true })
    .eq('user_id', userId);

  if (sessErr) {
    return NextResponse.json({ error: 'Failed to fetch usage' }, { status: 500 });
  }

  const used = totalUsed ?? 0;
  const remaining = Math.max(0, totalEarned - used);

  return NextResponse.json({
    credits_remaining: remaining,
    total_earned: totalEarned,
    total_used: used,
  });
}
